# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ar_rinit_rcpp <- function(nparticles, theta, rand, dimension) {
    .Call('_CoupledPIMH_ar_rinit_rcpp', PACKAGE = 'CoupledPIMH', nparticles, theta, rand, dimension)
}

ar_rtransition_rcpp <- function(xparticles, theta, time, rand, dimension, A) {
    .Call('_CoupledPIMH_ar_rtransition_rcpp', PACKAGE = 'CoupledPIMH', xparticles, theta, time, rand, dimension, A)
}

indexmatching_cpp <- function(w1, w2, ndraws) {
    .Call('_CoupledPIMH_indexmatching_cpp', PACKAGE = 'CoupledPIMH', w1, w2, ndraws)
}

create_A_ <- function(alpha, d) {
    .Call('_CoupledPIMH_create_A_', PACKAGE = 'CoupledPIMH', alpha, d)
}

levydriven_rtransition_rand_cpp <- function(nparticles, theta) {
    .Call('_CoupledPIMH_levydriven_rtransition_rand_cpp', PACKAGE = 'CoupledPIMH', nparticles, theta)
}

levydrivenmultifactor_rtransition_rand_cpp <- function(nparticles, theta) {
    .Call('_CoupledPIMH_levydrivenmultifactor_rtransition_rand_cpp', PACKAGE = 'CoupledPIMH', nparticles, theta)
}

one_step_lorenz_vector <- function(xparticles, tstart, tend, h, parameters) {
    .Call('_CoupledPIMH_one_step_lorenz_vector', PACKAGE = 'CoupledPIMH', xparticles, tstart, tend, h, parameters)
}

lorenz_generate_randomness_cpp <- function(nparticles, datalength) {
    .Call('_CoupledPIMH_lorenz_generate_randomness_cpp', PACKAGE = 'CoupledPIMH', nparticles, datalength)
}

lorenz_perturb_randomness_cpp <- function(randomness, rho) {
    .Call('_CoupledPIMH_lorenz_perturb_randomness_cpp', PACKAGE = 'CoupledPIMH', randomness, rho)
}

median_rcpp <- function(x) {
    .Call('_CoupledPIMH_median_rcpp', PACKAGE = 'CoupledPIMH', x)
}

multinomial_resampling_n_ <- function(weights, ndraws) {
    .Call('_CoupledPIMH_multinomial_resampling_n_', PACKAGE = 'CoupledPIMH', weights, ndraws)
}

coupled_multinomial_resampling_n_ <- function(weights1, weights2, ndraws) {
    .Call('_CoupledPIMH_coupled_multinomial_resampling_n_', PACKAGE = 'CoupledPIMH', weights1, weights2, ndraws)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('_CoupledPIMH_rmvnorm', PACKAGE = 'CoupledPIMH', nsamples, mean, covariance)
}

rmvnorm_transpose <- function(nsamples, mean, covariance) {
    .Call('_CoupledPIMH_rmvnorm_transpose', PACKAGE = 'CoupledPIMH', nsamples, mean, covariance)
}

rmvnorm_transpose_cholesky <- function(nsamples, mean, cholesky_covariance) {
    .Call('_CoupledPIMH_rmvnorm_transpose_cholesky', PACKAGE = 'CoupledPIMH', nsamples, mean, cholesky_covariance)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('_CoupledPIMH_dmvnorm', PACKAGE = 'CoupledPIMH', x, mean, covariance)
}

dmvnorm_transpose <- function(x, mean, covariance) {
    .Call('_CoupledPIMH_dmvnorm_transpose', PACKAGE = 'CoupledPIMH', x, mean, covariance)
}

dmvnorm_transpose_cholesky <- function(x, mean, cholesky_covariance) {
    .Call('_CoupledPIMH_dmvnorm_transpose_cholesky', PACKAGE = 'CoupledPIMH', x, mean, cholesky_covariance)
}

one_step_pz_vector <- function(xparticles, alphas, t, parameters) {
    .Call('_CoupledPIMH_one_step_pz_vector', PACKAGE = 'CoupledPIMH', xparticles, alphas, t, parameters)
}

rinitial_SVLevy_cpp <- function(N, t, xi, w2, lambda) {
    .Call('_CoupledPIMH_rinitial_SVLevy_cpp', PACKAGE = 'CoupledPIMH', N, t, xi, w2, lambda)
}

rtransition_SVLevy_cpp <- function(Xold, t_1, t, xi, w2, lambda) {
    .Call('_CoupledPIMH_rtransition_SVLevy_cpp', PACKAGE = 'CoupledPIMH', Xold, t_1, t, xi, w2, lambda)
}

dobs_SVLevy_cpp <- function(Yt, Xts, mu, beta, log) {
    .Call('_CoupledPIMH_dobs_SVLevy_cpp', PACKAGE = 'CoupledPIMH', Yt, Xts, mu, beta, log)
}

d1logdobs_SVLevy_cpp <- function(Yt, Xts, mu, beta) {
    .Call('_CoupledPIMH_d1logdobs_SVLevy_cpp', PACKAGE = 'CoupledPIMH', Yt, Xts, mu, beta)
}

d2logdobs_SVLevy_cpp <- function(Yt, Xts, mu, beta) {
    .Call('_CoupledPIMH_d2logdobs_SVLevy_cpp', PACKAGE = 'CoupledPIMH', Yt, Xts, mu, beta)
}

systematic_resampling_n_ <- function(weights, ndraws, u) {
    .Call('_CoupledPIMH_systematic_resampling_n_', PACKAGE = 'CoupledPIMH', weights, ndraws, u)
}

